### ISSUE TITLE
Crash after a tournament fight in surface_convert_to_grayscale()

### ISSUE THREAD

**Issue by mrannanj** [omf2097/openomf#720]
I had a crash with the following backtrace:
```
#0  surface_convert_to_grayscale (sur=0x5c5ae00e4188, pal=0x5c5ae02f6380, range_start=208, range_end=223) at /home/martti/gh/openomf/src/video/surface.c:144
144            idx = sur->data[i];
[Current thread is 1 (Thread 0x7bea3b84d840 (LWP 325780))]
(gdb) p *sur
$1 = {guid = 1795, w = 140, h = 100, transparent = -1, data = 0x0}
(gdb) bt
#0  surface_convert_to_grayscale (sur=0x5c5ae00e4188, pal=0x5c5ae02f6380, range_start=208, range_end=223) at /home/martti/gh/openomf/src/video/surface.c:144
#1  0x00005c5adecba476 in har_screencaps_compress (caps=0x5c5ae00e4170, pal=0x5c5ae02f6380, id=1) at /home/martti/gh/openomf/src/game/utils/har_screencap.c:56
#2  0x00005c5adec957a1 in arena_end (sc=0x5c5ae00e4020) at /home/martti/gh/openomf/src/game/scenes/arena.c:269
#3  0x00005c5adec9850f in arena_dynamic_tick (scene=0x5c5ae00e4020, paused=0) at /home/martti/gh/openomf/src/game/scenes/arena.c:1023
#4  0x00005c5adec9497f in scene_dynamic_tick (scene=0x5c5ae00e4020, paused=0) at /home/martti/gh/openomf/src/game/protos/scene.c:194
#5  0x00005c5adec7ab3b in game_state_dynamic_tick (gs=0x5c5ae00e3f30, replay=false) at /home/martti/gh/openomf/src/game/game_state.c:713
#6  0x00005c5adec5734f in engine_run (init_flags=0x7ffcb25bf070) at /home/martti/gh/openomf/src/engine.c:271
#7  0x00005c5adec56a48 in main (argc=1, argv=0x7ffcb25bf298) at /home/martti/gh/openomf/src/main.c:239
```
The crash happened after the fight was over, but I was still able to move with my Jaguar.

**Comment by mrannanj** [comment]
Haven't seen this again, closing for now.

**Comment by Nopey** [comment]
Occurs whenever the har screencap fails (say, if the win-pose is interrupted by a projectile).
Will be fixed in PR https://github.com/omf2097/openomf/pull/793
